[package]
name = "big_o"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lstsq = "0.4"
nalgebra = "0.31"
float-cmp = "0.9.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"
rand = "0.8.5"
