name: Build And Test

on:
  push:
  pull_request:
    branches:
    - main
    - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build And Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose --no-fail-fast -- --test-threads=1

    - name: Clippy
      run: cargo clippy
