name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger for any branch

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  TERM: xterm-256color

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - stable
        - beta
        - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose --no-fail-fast -- --test-threads=1

    - name: Clippy
      run: cargo clippy --all-targets --all --tests --all-features -- -Dclippy::all 
