name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger for any branch

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  TERM: xterm-256color

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-

      - name: Test
        run: cargo test --verbose --no-fail-fast -- --test-threads=1 --color always

  clippy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable && rustup component add clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-clippy-
            ${{ runner.os }}-cargo-

      - name: Clippy
        run: cargo clippy --all-targets --all --tests --all-features -- -Dclippy::all

  fmt:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable && rustup component add rustfmt
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-fmt-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-fmt-
            ${{ runner.os }}-cargo-

      - name: Format
        run: cargo fmt --all -- --check

  keepsorted:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install keepsorted
        run: cargo install keepsorted
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-keepsorted-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-keepsorted-
            ${{ runner.os }}-cargo-

      - name: Keepsorted
        run: |
          git ls-files -co --exclude-standard \
            | grep -vE '^misc/|^tests/|^README.md' \
            | xargs -I {} bash -c "keepsorted '{}' --features gitignore,rust_derive_canonical" {}
          git diff --exit-code
